runtime: go111

env: standard
instance_class: F1
handlers:
  - url: '/.*'
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  SEND_TO: "<YOUR_MAIL_TO>"
  WEBHOOKS_TO: "<YOUR_MAIL_TO>"
  SEND_SUBJECT: "<YOUR_MAIL_SUBJECT>"
  WEBHOOKS_SUBJECT: "<YOUR_MAIL_SUBJECT>"
